### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shooter27** [acdvorak/jquery.caret#1] opened 2014-03-24 09:03 UTC
$('#e_con_name').caret();    return an Object and not a number . Let me know where I'm wrong. Thanks.

**Comment by acdvorak** [comment] 2014-03-25 21:26
Please provide the following information and I'll be happy to help:
1.  Include a full code sample (including **both** HTML **_and_** JavaScript) so I can see what you're trying to do.  Make sure to use [Syntax Highlighting](https://help.github.com/articles/github-flavored-markdown#syntax-highlighting) so the code is easy to read.
2.  Is `#e_con_name` an `<input>` or `<textarea>` element?  If you try using the plugin on any other type of element it will return `undefined`.
3.  Which browser version(s) are experiencing this issue?
4.  Does the issue occur on more than one computer?

Thanks!

**Comment by acdvorak** [comment] 2014-05-01 02:15
Closing this issue.  If anyone is able to reproduce the problem and can provide more detailed information to help me track down the cause, I'll be happy to reopen it.

**Closed as completed by acdvorak** 2014-05-01 02:15 UTC

**Comment by bboydflo** [comment] 2017-07-14 12:36
Hi, does the plugin check if the setSelectionRange is supported on input with type number? I have tested the plugin and it works on an older Android WebView but not on in latest chrome. 

Also, check this article: https://meowni.ca/posts/a-story-about-input/
